services:
  db:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_PASSWORD: local_ks_postgres_db
      POSTGRES_DB: resume
      POSTGRES_USER: resume
    ports:
      - 15432:5432
    volumes:
      - ./volume/db:/var/lib/postgresql/data
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    container_name: postgresql_ks
