spring:
  application:
    name: resume-project
  datasource:
    #driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:15432/resume?charSet=UTF-8
    username: resume
    password: local_ks_postgres_db
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://localhost:15432/resume?charSet=UTF-8
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  messages:
    basename: messages
    fallback-to-system-locale: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB


server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.ks.resumeproject.**.domain
  config-location: classpath:mybatis-config.xml

springdoc:
  version: '@springdoc.version@'
  api-docs:
    version: openapi_3_1
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: true


jwt:
  secret: 511b0f52445969be5e0cedb7e7f89a183758eeb27c7270711c83cc057222587
