spring:
  application:
    name: resume-project
  datasource:
    #driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:15432/resume?charSet=UTF-8
    username: resume
    password: ***REMOVED***
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://localhost:15432/resume?charSet=UTF-8
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  messages:
    basename: messages
    fallback-to-system-locale: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: ***REMOVED***
    password: ***REMOVED***
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
      auth-code-expiration-millis: 1800000

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.ks.resumeproject.**.domain
  config-location: classpath:mybatis-config.xml

springdoc:
  version: '@springdoc.version@'
  api-docs:
    version: openapi_3_1
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: true

allowed:
  origins: http://localhost:5173/

jwt:
  secret: ***REMOVED***

