spring:
  application:
    name: resume-project
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/resume
    username: resume
    password: ***REMOVED***
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

springdoc:
  version: '@springdoc.version@'
  api-docs:
    version: openapi_3_1
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: true
  group-configs:
    - group: test
      paths-to-match: /test/**

